### ISSUE TITLE
fcn.conf 配置文件如何调用？

### ISSUE THREAD

**Issue by smounives** [boywhp/fcn#13]
您好，请问加什么参数调用fcn.conf配置文件？谢谢。

**Comment by boywhp** [comment]
将fcn执行文件和fcn.conf放一个目录下, 无需参数直接执行即可

**Comment by smounives** [comment]
可否考虑加个参数调用其他目录的配置文件？例如加个 --conf /etc/fcn.conf

**Comment by boywhp** [comment]
你可以用linux的 **ln**创建一个软链接看看行不行
