### ISSUE TITLE
Ping不通

### ISSUE THREAD

**Issue by duffercn** [boywhp/fcn#19]
OpenWRT做服务端，Windows和安卓都能连上获得DHCP地址，但是就是Ping不通10.10.0.1。请问这个怎么回事？

**Comment by duffercn** [comment]
嗯，还是Ping不通。不过如果用Windows PC做服务端，安卓做客户端，虽然Ping不通但可以访问局域网其他机器；但如果用OpenWRT做服务端，安卓做客户端，Ping不通也不能访问其他局域网机器。问题会在iptable吗？

**Comment by boywhp** [comment]
FCN在OpenWRT路由器上默认NAT网卡可能有误, 可以尝试手工指定[nat_nic]=局域网网卡名

**Comment by duffercn** [comment]
嗯。。默认用的是pppoe的网卡，制定eth0之后，连都连不上了，很快闪过认证等信息后，就是断开了。
