### ISSUE TITLE
android客户端不能实际工作

### ISSUE THREAD

**Issue by wooego** [boywhp/fcn#25]
在树莓派3上跑了个服务端，同时下了一个Linux客户端和Android客户端，Linux客户端运行成功后分配地址10.10.0.2，并可以成功连接树莓派3。Android客户端运行后，手机右上角成功显示了一个VPN，客户端上也显示出分配的IP：10.10.0.3,可是就是不能成功的连接到树莓派3的10.10.0.1上，也无法ping通。
所以想问，有朋友成功使用Android客户端了么？我的是版本为Android7.1.1的手机。

**Comment by boywhp** [comment]
你直接访问服务端局域网地址看看, 不要访问10.10.0.1

**Comment by wooego** [comment]
服务端局域网地址一个是路由器分配的192.168.0.102,这个地址我手机用数据网连接的时候肯定连接不上。
另一个地址就是10.10.0.1了，确实连接不上。

**Comment by boywhp** [comment]
你最好实际测试看看192.168.0.102这个地址, 以及这个局域网网段是否能够在手机上访问, 设计上是可以的

**Comment by wooego** [comment]
是的，我想当然了。测试192.168.0.xx可行。颠覆了我的认知。
