### ISSUE TITLE
android客户端突然不能正常工作

### ISSUE THREAD

**Issue by wooego** [boywhp/fcn#26]
本来可以正常工作的。这几天突然在服务器查询成功后服务器认证成功后，就提示未连接。请问是服务器端做限制了么？

**Comment by wooego** [comment]
请问有办法查询流量配额情况么？虽然手机端不能访问，可是我电脑端方式可以支持登录连接。

**Comment by boywhp** [comment]
需要管理员到服务器才能查询, 客户无法查询自己的流量配额
如果电脑能够连接, 说明是正常的, 目前android版本存在BUG, 
你可以关注即将发布的3.5正式版, 会对android版本进行修复
