### ISSUE TITLE
请问：路由器部署了FCN后怎样添加多用户啊？？？

### ISSUE THREAD

**Issue by ppcfuns** [boywhp/fcn#30]
请问：路由器部署了FCN后怎样添加多用户啊？？？

需要多个用户同时接入，，请问该怎么配置？？

windows 上好像可以添加多用户的，，

**Comment by boywhp** [comment]
通过windows版本导出用户列表文件，拷到Linux系统，服务端配置文件[authfile]指向该文件即可
