### ISSUE TITLE
请问怎样使fcn的"客户"端在win10下开机自动连接"服务"端?

### ISSUE THREAD

**Issue by efaun** [boywhp/fcn#34]

**Comment by boywhp** [comment]
客户端添加好服务度配置后， Windows托盘菜单， 找到FCN图标， 鼠标右键， 登录自动连接菜单，选中你要的服务端名称即可

**Comment by efaun** [comment]
不行啊, 在登录自动连接菜单，选中服务端,并添加系统启动项,重启以后只是打开了客户端,并没有自动连接

**Comment by boywhp** [comment]
服务端和客户端是否均为github Release里面最新3.8版本? 或者你尝试删除Fcn.dat重新尝试看看
