### ISSUE TITLE
请问安卓手机怎么与电脑链接？

### ISSUE THREAD

**Issue by klxq520** [boywhp/fcn#39]
想在别的地方用手机访问电脑的文件，有解决方法么？

**Comment by boywhp** [comment]
使用FCN安卓版本连上服务端后, 直接用HTTP/FTP/SMB客户端访问即可

**Comment by klxq520** [comment]
> 使用FCN安卓版本连上服务端后, 直接用HTTP/FTP/SMB客户端访问即可

有哪些客户端可以推荐下么？
