### ISSUE TITLE
帮我弄个更美观的安卓客户端

### ISSUE THREAD

**Issue by kfyidrig** [boywhp/fcn#41]
可不要可以帮我弄个更美观的安卓客户端，还有，服务端可不可以放到我的Linux服务器，毕竟电脑不可能一直开启啊，我真心想弄，可以的话买付费

**Comment by boywhp** [comment]
能用就行，美观不要在意，我也是临时学的安卓开发，没太多时间，凑合用吧
Linux服务端不是有现成的？主页那么大的下载连接，没看到？
