### ISSUE TITLE
Fcn使用过程发的问题反馈

### ISSUE THREAD

**Issue by hongdodo-td** [boywhp/fcn#43]
1、没有备注服务器名称和IP的地方
2、连接服务器后，需要知道对方具体的IP，通过第三方软件才能登陆，很不方便

**Comment by boywhp** [comment]
1. 客户端连接参数，编辑，输入服务端名称行，NAME/NAME备注
2. 可以通过虚拟网卡网段登录，默认服务端FCN虚拟网卡10.10.0.1
