### ISSUE TITLE
fcn服务端中断后，客户端网络同局域网无法访问

### ISSUE THREAD

**Issue by winklejude** [boywhp/fcn#48]
在本地两台服务器上测试fcn，centos6.7，一台服务端，一台客户端，已经正常连接。
fcn网络10.10段，本地局域网172.16段。
如果此时中断服务端，同客户端在同一局域网的其他设备通过本地局域172.16网段也无法访问客户机了。
ping不通，ssh也不通。
只有重启服务端，过一分钟，客户机才能访问。
按正常来讲，服务端掉线后，客户机自己的局域网应该是可以访问的吧。为什么本地ip段也不通了？

**Comment by boywhp** [comment]
fcn服务端默认推送本地局域网网段到客户端，也就是172.16段默认是走服务端转发的，你服务端掉了自然访问不了了。  
而且fcn虚拟网卡是断线不断网卡的，会自动断线重连，所以会出现你说的这种情况
