### ISSUE TITLE
移动宽带无法建立p2p连接

### ISSUE THREAD

**Issue by jiaohaolin** [boywhp/fcn#49]
试用了下，感觉跟有个开源软件zerotier 应该是类似的，用起来的问题也是一样的，没法建立p2p连接，走的还是公共服务转发，不知道移动限制了啥，希望大神们有空可以搞一搞给解决了

**Comment by boywhp** [comment]
p2p无法确保一定能成功，尤其是移动流量下，基本不可能P2P
你可以考虑FCN付费账号
