### ISSUE TITLE
求助啊，客户端连接服务端的时候，显示应用层NAT不支持本机连接

### ISSUE THREAD

**Issue by aszx-fyh** [boywhp/fcn#51]
![QQ拼音截图20200411093645](https://user-images.githubusercontent.com/16113553/79032314-08434480-7bd8-11ea-8604-4717b00d69e3.png)

**Comment by boywhp** [comment]
FCN需要在两天不同电脑上，分别运行服务端和客户端模式进行连接
你可以将本机的fcn.dat配置文件删除，重新添加客户端连接参数
