### ISSUE TITLE
windows10 WSL子系统中客户端启动失败

### ISSUE THREAD

**Issue by codestepwell** [boywhp/fcn#52]
在win10 WSL子系统Debian和Ubuntu中以客户端模式连结服务端时，提示：
FCN SERVER:free.xfconnect.com
FCN LINK:UDP
FCN init_tun_dev failed

WSL环境中有无可能通过某些配置后正常运行？

**Comment by boywhp** [comment]
FCN客户端模式必须要开启tun虚拟网卡,需要root权限，而且目前WSL子系统好像不支持虚拟网卡吧
