### ISSUE TITLE
能开发384版梅林固件吗？

### ISSUE THREAD

**Issue by huyhwb** [boywhp/fcn#53]
384版梅林无法安装，提示如下
【2020年05月06日 14:31:42】: ====================== step 1 ===========================
【2020年05月06日 14:31:42】: 开启软件离线安装！
【2020年05月06日 14:31:42】: /tmp/upload目录下检测到上传的离线安装包fcn.tar.gz，大小：362.5K
【2020年05月06日 14:31:42】: 尝试解压离线安装包离线安装包
【2020年05月06日 14:31:42】: 解压完成！
【2020年05月06日 14:31:42】: 你上传的离线安装包不是arm384平台的离线包！！！
【2020年05月06日 14:31:42】: 请上传正确的离线安装包！！！
【2020年05月06日 14:31:42】: 删除相关文件并退出...
【2020年05月06日 14:31:42】: ======================== end ============================

**Comment by boywhp** [comment]
精力有限，请自行购买GL-MT300NV2路由器，并刷FCN定制的Padavan固件，QQ群文件下载
