### ISSUE TITLE
Linux LEDE-X64 4.9.54 版本不支持

### ISSUE THREAD

**Issue by 18257990357** [boywhp/fcn#7]
Linux LEDE-X64 4.9.54 版本不支持，无法运行。希望编译一个。

**Comment by boywhp** [comment]
LEDE x64的版本不太常见啊, 计划下个版本支持LEDE

**Comment by 18257990357** [comment]
是的。。X86架构的OPENWRT、LEDE比较小众，玩的人不多。多谢
